services:
  kali-logisim:
    build:
      context: .
      args:
        LOGISIM_VERSION: "4.0.0"
    container_name: kali-logisim
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TITLE=Kali + Logisim
    ports:
      - "3011:3000"
      - "3009:3001"
    volumes:
      - ./config:/config
    shm_size: "1gb"
    restart: unless-stopped
